import React from "react";
import Image from "next/image";
import { mainFont } from "@/components/UI/Mainfontt";
import { FooterSection } from "@/components/Homepage/Footer/FooterSection";
import { global } from "styled-jsx/css";
const privacy_policy = () => {
  return (
    <div>
      <div className="w-full h flex items-center relative">
        {/* Dynamic half-circle blur effect */}
        <div className="absolute w-[80%] md:h-[700px] h-[343px] md:-top-[460px] -top-[200px] left-1/2 -translate-x-1/2 opacity-80 bg-gradient-to-t from-transparent via-[#007fa97e] to-transparent rounded-full blur-md md:blur-xl" />

        {/* Content section with higher z-index */}
        <div className="w-full flex flex-col relative z-10">
          <div className="md:mt-[10%] text-center mt-[215px] mx-auto md:w-[76%] w-[90%]">
            {/* Heading text */}
            <div
              style={{ fontFamily: mainFont.style.fontFamily }}
              className="font-semibold md:text-[72px]  text-[40px] md:leading-[72px] leading-[40px] uppercase text-white"
            >
              Privacy Policy
            </div>
          </div>

          <div className="flex justify-center mx-6 ">
            <div className="max-w-[1400px] sm:mx-6 my-6  text-white">
              <div>
                <p>
                  Code Visionary Studio (“we”, “our”, or “us”) is committed to
                  protecting your privacy. This Privacy Policy explains how your
                  personal information is collected, used, and disclosed by Code
                  Visionary Studio.
                </p>

                <p>
                  This Privacy Policy applies to our website,{" "}
                  <a href="https://www.codevisionarystudio.com/">
                    https://www.codevisionarystudio.com/
                  </a>
                  , and its associated subdomains (collectively, our “Service”).
                  By accessing or using our Service, you signify that you have
                  read, understood, and agree to our collection, storage, use,
                  and disclosure of your personal information as described in
                  this Privacy Policy and our Terms of Service.
                </p>
              </div>
              <div>
                <h2>
                  <strong>Definitions and Key Terms</strong>
                </h2>

                <p>
                  <strong>Cookie:</strong> Small amount of data generated by a
                  website and saved by your web browser. It is used to identify
                  your browser, provide analytics, and remember information
                  about you such as your language preference or login
                  information.
                </p>

                <p>
                  <strong>Company:</strong> When this policy mentions “Company”,
                  “we”, “us,” or “our,” it refers to Code Visionary Studio,
                  13-239/2/NEW Bidyasagar Park Road at Saparaipur Bidyasagar
                  Park SARANYA NIBAS District :- South 24 Parganas Pincode :-
                  700142, India that is responsible for your information under
                  this Privacy Policy.
                </p>

                <p>
                  <strong>Country:</strong> Where Code Visionary Studio or the
                  owners/founders of CodeVisionaryStudio are based, in this
                  case, is India.
                </p>

                <p>
                  <strong>Customer:</strong> Refers to the company, organization
                  or person that signs up to use the CodeVisionaryStudio Service
                  to manage the relationships with your consumers or service
                  users.
                </p>

                <p>
                  <strong>Device:</strong> Any internet-connected device such as
                  a phone, tablet, computer or any other device that can be used
                  to visit Code Visionary Studio and use the services.
                </p>

                <p>
                  <strong>IP Address:</strong> Every device connected to the
                  Internet is assigned a number known as an Internet protocol
                  (IP) address. These numbers are usually assigned in geographic
                  blocks. An IP address can often be used to identify the
                  location from which a device is connecting to the Internet.
                </p>

                <p>
                  <strong>Personnel:</strong> Refers to those individuals who
                  are employed by CodeVisionaryStudio or are under contract to
                  perform a service on behalf of one of the parties.
                </p>

                <p>
                  <strong>Personal Data:</strong> Any information that directly,
                  indirectly, or in connection with other information including
                  a personal identification number allows for the identification
                  or identifiability of a natural person.
                </p>

                <p>
                  <strong>Service:</strong> Refers to the service provided by
                  CodeVisionaryStudio as described in the relative terms (if
                  available) and on this platform.
                </p>

                <p>
                  <strong>Third-party service:</strong> Refers to advertisers,
                  contest sponsors, promotional and marketing partners, and
                  others who provide our content or whose products or services
                  we think may interest you.
                </p>

                <p>
                  <strong>Website:</strong> Code Visionary Studio’s site, which
                  can be accessed via this URL:{" "}
                  <a href="https://www.codevisionarystudio.com/">
                    https://www.codevisionarystudio.com/
                  </a>
                </p>

                <p>
                  <strong>You:</strong> A person or entity that is registered
                  with CodeVisionaryStudio to use the Services.
                </p>
              </div>
              <div>
                <h2>
                  <strong>What Information Do We Collect?</strong>
                </h2>
                <p>
                  We collect information from you when you visit our service,
                  register, place an order, subscribe to our newsletter, respond
                  to a survey, or fill out a form.
                </p>
                <ul>
                  <li>Name/Username</li>
                  <li>Phone Number</li>
                  <li>Email Address</li>
                  <li>Mailing Address</li>
                  <li>Job Titles</li>
                  <li>Billing Address</li>
                  <li>Cookies and Usage Data</li>
                </ul>
              </div>
              <div>
                <h2>
                  <strong>How Do We Use The Information We Collect?</strong>
                </h2>
                <p>
                  Any of the information we collect from you may be used in one
                  of the following ways:
                </p>
                <ul>
                  <li>
                    To personalize your experience (your information helps us to
                    better respond to your individual needs)
                  </li>
                  <li>
                    To improve our service (we continually strive to improve our
                    service offerings based on the information and feedback we
                    receive from you)
                  </li>
                  <li>
                    To improve customer service (your information helps us to
                    more effectively respond to your customer service requests
                    and support needs)
                  </li>
                  <li>To process transactions</li>
                  <li>
                    To administer a contest, promotion, survey or other site
                    feature
                  </li>
                  <li>To send periodic emails</li>
                </ul>

                <h2>
                  <strong>
                    When do we use customer information from third parties?
                  </strong>
                </h2>
                <p>
                  We receive some information from third parties when you
                  contact us. For example, when you submit your email address to
                  us to show interest in becoming our customer, we receive
                  information from a third party that provides automated fraud
                  detection services to us. We also occasionally collect
                  information that is made publicly available on social media
                  websites. You can control how much of your information social
                  media websites make public by visiting these websites and
                  changing your privacy settings.
                </p>
              </div>
              <div>
                <h2>
                  <strong>
                    Do we share the information we collect with third parties?
                  </strong>
                </h2>
                <p>
                  We may share the information that we collect, both personal
                  and non-personal, with third parties such as advertisers,
                  contest sponsors, promotional and marketing partners, and
                  others who provide our content or whose products or services
                  we think may interest you. We may also share it with our
                  current and future affiliated companies and business partners.
                  If we are involved in a merger, asset sale, or other business
                  reorganization, we may also share or transfer your personal
                  and non-personal information to our successors-in-interest.
                </p>

                <p>
                  We may engage trusted third-party service providers to perform
                  functions and provide services to us, such as hosting and
                  maintaining our servers and our service, database storage and
                  management, email management, storage, marketing, credit card
                  processing, customer service, and fulfilling orders for
                  products and services you may purchase through our platform.
                  We will likely share your personal information, and possibly
                  some non-personal information, with these third parties to
                  enable them to perform these services for us and for you.
                </p>

                <p>
                  We may share portions of our log file data, including IP
                  addresses, for analytics purposes with third parties such as
                  web analytics partners, application developers, and ad
                  networks. If your IP address is shared, it may be used to
                  estimate general location and other technographics such as
                  connection speed, shared location usage, and the type of
                  device used to visit the service. They may aggregate
                  information about our advertising and what you see on the
                  service and then provide auditing, research, and reporting for
                  us and our advertisers.
                </p>

                <p>
                  We may also disclose personal and non-personal information
                  about you to government or law enforcement officials or
                  private parties as we, in our sole discretion, believe
                  necessary or appropriate in order to respond to claims, legal
                  processes (including subpoenas), to protect our rights and
                  interests or those of a third party, the safety of the public
                  or any person, to prevent or stop any illegal, unethical, or
                  legally actionable activity, or to otherwise comply with
                  applicable court orders, laws, rules, and regulations.
                </p>
              </div>
              <div>
                <h2>
                  <strong>
                    Where and when is information collected from customers and
                    end users?
                  </strong>
                </h2>
                <p>
                  We will collect personal information that you submit to us. We
                  may also receive personal information about you from third
                  parties as described above.
                </p>

                <h2>
                  <strong>How do we use your email address?</strong>
                </h2>
                <p>
                  By submitting your email address on this website, you agree to
                  receive emails from us. You can cancel your participation in
                  any of these email lists at any time by clicking on the
                  opt-out link or other unsubscribe option that is included in
                  the respective email. We only send emails to people who have
                  authorized us to contact them, either directly, or through a
                  third party. We do not send unsolicited commercial emails,
                  because we hate spam as much as you do. By submitting your
                  email address, you also agree to allow us to use your email
                  address for customer audience targeting on sites like
                  Facebook, where we display custom advertising to specific
                  people who have opted-in to receive communications from us.
                  Email addresses submitted only through the order processing
                  page will be used for the sole purpose of sending you
                  information and updates pertaining to your order. If, however,
                  you have provided the same email to us through another method,
                  we may use it for any of the purposes stated in this Policy.
                </p>
                <p>
                  <strong>Note:</strong> If at any time you would like to
                  unsubscribe from receiving future emails, we include detailed
                  unsubscribe instructions at the bottom of each email.
                </p>

                <h2>
                  <strong>
                    Could my information be transferred to other countries?
                  </strong>
                </h2>
                <p>
                  We are incorporated in India. Information collected via our
                  website, through direct interactions with you, or from use of
                  our help services may be transferred from time to time to our
                  offices or personnel, or to third parties, located throughout
                  the world, and may be viewed and hosted anywhere in the world,
                  including countries that may not have laws of general
                  applicability regulating the use and transfer of such data. To
                  the fullest extent allowed by applicable law, by using any of
                  the above, you voluntarily consent to the trans-border
                  transfer and hosting of such information.
                </p>

                <h2>
                  <strong>
                    Is the information collected through our service secure?
                  </strong>
                </h2>
                <p>
                  We take precautions to protect the security of your
                  information. We have physical, electronic, and managerial
                  procedures to help safeguard, prevent unauthorized access,
                  maintain data security, and correctly use your information.
                  However, neither people nor security systems are foolproof,
                  including encryption systems. In addition, people can commit
                  intentional crimes, make mistakes, or fail to follow policies.
                  Therefore, while we use reasonable efforts to protect your
                  personal information, we cannot guarantee its absolute
                  security. If applicable law imposes any non-disclaimable duty
                  to protect your personal information, you agree that
                  intentional misconduct will be the standard used to measure
                  our compliance with that duty.
                </p>
              </div>
              <div>
                <h2>
                  <strong>Can I update or correct my information?</strong>
                </h2>
                <p>
                  The rights you have to request updates or corrections to the
                  information we collect depend on your relationship with us.
                  Personnel may update or correct their information as detailed
                  in our internal company employment policies. Customers have
                  the right to request the restriction of certain uses and
                  disclosures of personally identifiable information as follows:
                </p>
                <ul>
                  <li>
                    Update or correct your personally identifiable information
                  </li>
                  <li>
                    Change your preferences with respect to communications and
                    other information you receive from us
                  </li>
                  <li>
                    Delete the personally identifiable information maintained
                    about you on our systems by canceling your account
                  </li>
                </ul>
                <p>
                  To protect your privacy and security, we may take reasonable
                  steps (such as requesting a unique password) to verify your
                  identity before granting you profile access or making
                  corrections.
                </p>

                <h2>
                  <strong>Personnel</strong>
                </h2>
                <p>
                  If you are one of our workers or applicants, we collect
                  information you voluntarily provide to us. We use the
                  information collected for Human Resources purposes in order to
                  administer benefits to workers and screen applicants. You may
                  contact us to:
                </p>
                <ul>
                  <li>Update or correct your information</li>
                  <li>
                    Change your preferences with respect to communications and
                    other information you receive from us
                  </li>
                  <li>
                    Receive a record of the information we have relating to you
                  </li>
                </ul>

                <h2>
                  <strong>Sale of Business</strong>
                </h2>
                <p>
                  We reserve the right to transfer information to a third party
                  in the event of:
                </p>
                <ul>
                  <li>
                    A sale, merger, or other transfer of all or substantially
                    all of our assets
                  </li>
                  <li>A discontinuation of our business</li>
                  <li>A bankruptcy, reorganization, or similar proceeding</li>
                </ul>
                <p>
                  Provided that the third party agrees to adhere to the terms of
                  this Privacy Policy.
                </p>

                <h2>
                  <strong>Affiliates</strong>
                </h2>
                <p>
                  We may disclose information (including personal information)
                  about you to our Corporate Affiliates. For purposes of this
                  Privacy Policy, a &quot;Corporate Affiliate&quot; means any person or
                  entity that directly or indirectly controls, is controlled by,
                  or is under common control with us. Any information relating
                  to you that we provide to our Corporate Affiliates will be
                  treated by those Corporate Affiliates in accordance with this
                  Privacy Policy.
                </p>

                <h2>
                  <strong>How long do we keep your information?</strong>
                </h2>
                <p>
                  We keep your information only as long as necessary to provide
                  services to you and fulfill the purposes described in this
                  policy. When we no longer need to use your information and
                  there is no requirement for us to retain it to comply with
                  legal or regulatory obligations, we will either:
                </p>
                <ol>
                  <li>Remove it from our systems</li>
                  <li>
                    Depersonalize it so that it can no longer identify you
                  </li>
                </ol>
              </div>
              <div>
                <h2>
                  <strong>How long do we keep your information?</strong>
                </h2>
                <p>
                  We keep your information only so long as we need it to provide
                  service to you and fulfill the purposes described in this
                  policy. This is also the case for anyone that we share your
                  information with and who carries out services on our behalf.
                  When we no longer need to use your information and there is no
                  need for us to keep it to comply with our legal or regulatory
                  obligations, we’ll either remove it from our systems or
                  depersonalize it so that we can’t identify you.
                </p>
              </div>
              <div>
                <h2>
                  <strong>How do we protect your information?</strong>
                </h2>
                <p>
                  We implement a variety of security measures to maintain the
                  safety of your personal information when you place an order or
                  enter, submit, or access your personal information. We offer
                  the use of a secure server. All supplied sensitive/credit
                  information is transmitted via Secure Socket Layer (SSL)
                  technology and then encrypted into our Payment gateway
                  provider&apos;s database only to be accessible by those authorized
                  with special access rights to such systems, who are required
                  to keep the information confidential. After a transaction,
                  your private information (credit cards, social security
                  numbers, financials, etc.) is never kept on file. We cannot,
                  however, ensure or warrant the absolute security of any
                  information you transmit to us or guarantee that your
                  information on the Service may not be accessed, disclosed,
                  altered, or destroyed by a breach of any of our physical,
                  technical, or managerial safeguards.
                </p>

                <h2>
                  <strong>Governing Law</strong>
                </h2>
                <p>
                  The laws of India, excluding its conflicts of law rules, shall
                  govern this Agreement and your use of our service. Your use of
                  our service may also be subject to other local, state,
                  national, or international laws.
                </p>

                <h2>
                  <strong>Your Consent</strong>
                </h2>
                <p>
                  By using our service, registering an account, or making a
                  purchase, you consent to this Privacy Policy.
                </p>

                <h2>
                  <strong>Links to Other Websites</strong>
                </h2>
                <p>
                  This Privacy Policy applies only to the Services. The Services
                  may contain links to other websites not operated or controlled
                  by us. We are not responsible for the content, accuracy, or
                  opinions expressed on such websites, and we do not
                  investigate, monitor, or check their accuracy or completeness.
                  Please remember that when you use a link to go from the
                  Services to another website, our Privacy Policy is no longer
                  in effect. Your browsing and interaction on any other website,
                  including those that have a link on our platform, is subject
                  to that website’s own rules and policies. Such third parties
                  may use their own cookies or other methods to collect
                  information about you.
                </p>

                <h2>
                  <strong>Cookies</strong>
                </h2>
                <p>
                  We use “Cookies” to identify the areas of our website that you
                  have visited. A Cookie is a small piece of data stored on your
                  computer or mobile device by your web browser. We use Cookies
                  to personalize the content that you see on our website. Most
                  web browsers can be set to disable the use of Cookies.
                  However, if you disable Cookies, you may not be able to access
                  functionality on our website correctly or at all. We never
                  place Personally Identifiable Information in Cookies.
                </p>

                <h2>
                  <strong>Remarketing Services</strong>
                </h2>
                <p>
                  We use remarketing services. In digital marketing, remarketing
                  (or retargeting) is the practice of serving ads across the
                  internet to people who have already visited your website. It
                  allows your company to appear to “follow” people around the
                  internet by displaying ads on the websites and platforms they
                  use most.
                </p>

                <h2>
                  <strong>Kids’ Privacy</strong>
                </h2>
                <p>
                  We do not address anyone under the age of 13. We do not
                  knowingly collect personally identifiable information from
                  anyone under the age of 13. If you are a parent or guardian
                  and you are aware that your child has provided us with
                  personal data, please contact us. If we become aware that we
                  have collected Personal Data from anyone under the age of 13
                  without verification of parental consent, we take steps to
                  remove that information from our servers.
                </p>

                <h2>
                  <strong>Changes to Our Privacy Policy</strong>
                </h2>
                <p>
                  If we decide to change our privacy policy, we will post those
                  changes on this page and/or update the Privacy Policy
                  modification date below.
                </p>

                <h2>
                  <strong>Third-Party Services</strong>
                </h2>
                <p>
                  We may display, include, or make available third-party content
                  (including data, information, applications, and other products
                  or services) or provide links to third-party websites or
                  services (“Third-Party Services”).
                </p>
                <p>
                  You acknowledge and agree that we shall not be responsible for
                  any Third-Party Services, including their accuracy,
                  completeness, timeliness, validity, copyright compliance,
                  legality, decency, quality, or any other aspect thereof. We do
                  not assume and shall not have any liability or responsibility
                  to you or any other person or entity for any Third-Party
                  Services.
                </p>
                <p>
                  Third-Party Services and links thereto are provided solely as
                  a convenience to you, and you access and use them entirely at
                  your own risk and subject to such third parties’ terms and
                  conditions.
                </p>
              </div>
              <div>
                <h2>
                  <strong>Google Maps APIs</strong>
                </h2>
                <p>Google Maps API is a robust tool that can be used to:</p>
                <ul>
                  <li>Create a custom map</li>
                  <li>Develop a searchable map</li>
                  <li>Enable check-in functions</li>
                  <li>Display live data syncing with location</li>
                  <li>Plan routes</li>
                  <li>Create a mashup</li>
                </ul>
                <p>Additionally:</p>
                <ul>
                  <li>
                    Google Maps API may collect information from you and your
                    device for security purposes.
                  </li>
                  <li>
                    Google Maps API collects information that is held in
                    accordance with its Privacy Policy.
                  </li>
                </ul>
              </div>
              <div>
                <h2>
                  <strong>Cookies</strong>
                </h2>
                <p>
                  We use Cookies to enhance the performance and functionality of
                  our service, but they are not essential for its use. Without
                  these cookies, certain functionalities such as video playback
                  may become unavailable, and you may need to enter your login
                  details every time you visit our service as we would not be
                  able to remember that you had logged in previously.
                </p>

                <h2>
                  <strong>
                    Information about General Data Protection Regulation (GDPR)
                  </strong>
                </h2>
                <p>
                  We may collect and use information from you if you are from
                  the European Economic Area (EEA). This section explains how
                  and why this data is collected and how we ensure its
                  protection from unauthorized replication or misuse.
                </p>

                <h2>
                  <strong>What is GDPR?</strong>
                </h2>
                <p>
                  GDPR is an EU-wide privacy and data protection law that
                  regulates how the personal data of EU residents is handled by
                  companies and enhances the control EU residents have over
                  their personal data.
                </p>
              </div>
              <div>
                <h2>
                  <strong>What is Personal Data?</strong>
                </h2>
                <p>
                  Any data that relates to an identifiable or identified
                  individual. GDPR covers a broad spectrum of information that
                  could be used on its own or in combination with other pieces
                  of information to identify a person. Personal data extends
                  beyond a person’s name or email address. Some examples include
                  financial information, political opinions, genetic data,
                  biometric data, IP addresses, physical addresses, sexual
                  orientation, and ethnicity.
                </p>
                <p>
                  The Data Protection Principles include requirements such as:
                </p>
                <ul>
                  <li>
                    Personal data collected must be processed in a fair, legal,
                    and transparent way and should only be used in a way that a
                    person would reasonably expect.
                  </li>
                  <li>
                    Personal data should only be collected to fulfill a specific
                    purpose and should only be used for that purpose.
                    Organizations must specify why they need the personal data
                    when they collect it.
                  </li>
                  <li>
                    Personal data should be held no longer than necessary to
                    fulfill its purpose.
                  </li>
                  <li>
                    People covered by the GDPR have the right to access their
                    own personal data. They can also request a copy of their
                    data, and that their data be updated, deleted, restricted,
                    or moved to another organization.
                  </li>
                </ul>
              </div>
              <div>
                <h2>
                  <strong>Why is GDPR Important?</strong>
                </h2>
                <p>
                  GDPR introduces new requirements regarding how companies
                  should protect individuals’ personal data that they collect
                  and process. It also increases compliance stakes by imposing
                  greater fines for breaches. More importantly, it is a step
                  towards ensuring data privacy and security. We strongly
                  believe in the importance of data privacy and have implemented
                  solid security and privacy practices that exceed the
                  requirements of this regulation.
                </p>

                <h2>
                  <strong>
                    Individual Data Subject’s Rights – Data Access, Portability,
                    and Deletion
                  </strong>
                </h2>
                <p>
                  We are committed to assisting our customers in meeting the
                  data subject rights requirements of GDPR. All personal data is
                  processed and stored with fully vetted, Data Processing
                  Agreement (DPA) compliant vendors. We retain all conversations
                  and personal data for up to six years unless an account is
                  deleted. In such cases, we dispose of all data per our Terms
                  of Service and Privacy Policy, ensuring that no data is held
                  longer than 60 days.
                </p>
                <p>
                  If you work with EU customers, you must provide them with
                  access to update, retrieve, and remove their personal data.
                  Our system is designed to be self-service, enabling you to
                  access your data and that of your customers at any time.
                  Additionally, our customer support team is available to
                  address any concerns regarding our API and GDPR compliance.
                </p>

                <h2>
                  <strong>Contact Us</strong>
                </h2>
                <p>If you have any questions, feel free to reach out to us:</p>
                <ul>
                  <li>
                    <strong>Via Email:</strong> sales@codevisionarystudio.com
                  </li>
                  <li>
                    <strong>Via Phone Number:</strong> +91-8240833838
                  </li>
                  <li>
                    <strong>Via Website:</strong>{" "}
                    <a
                      href="https://www.codevisionarystudio.com/"
                      target="_blank"
                    >
                      https://www.codevisionarystudio.com/
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <FooterSection />
    </div>
  );
};

export default privacy_policy;
